name: build-test

on:
  push:
    branches:
      - develop
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: setup git config
      run: |
        git config user.name "blackbelt-oss"
        git config user.email "oss@blackbelt.hu"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g npm
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
