name: release

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Release Type (not yet used, can be anything)'
        required: true
        default: 'patch'

jobs:
  release:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_OSS_AUTOMATION_TOKEN }}
      GH_TOKEN: ${{ secrets.OSS_PAT }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: setup git config
        run: |
          git config user.name "blackbelt-oss"
          git config user.email "oss@blackbelt.hu"
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - run: npm i -g npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - run: npm run new-publish:ci
