name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The explicit version to set (e.g., 9.11.3)'
        required: true
        type: string

jobs:
  release:
    permissions:
      contents: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_OSS_AUTOMATION_TOKEN }}
      GH_TOKEN: ${{ secrets.OSS_PAT }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup git config
        run: |
          git config user.name "blackbelt-oss"
          git config user.email "oss@blackbelt.hu"

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build all packages
        run: pnpm build

      - name: Test all packages
        run: pnpm test

      - name: Bump version in all packages
        run: |
          npm version ${{ github.event.inputs.version }} --no-git-tag-version
          pnpm -r exec npm pkg set version=${{ github.event.inputs.version }}

      - name: Get new version from root package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Re-build all packages with new version
        run: pnpm build

      - name: Setup Node.js for publishing
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish packages to NPM
        run: pnpm -r publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_OSS_AUTOMATION_TOKEN }}

      - name: Push changes to repository
        run: |
          git push origin HEAD:${{ github.ref_name }} --follow-tags

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          body: 'New release v${{ steps.get_version.outputs.VERSION }}'
          draft: false
          prerelease: false
